version: '3.3'

volumes:

  postgres-data:
    driver: local

services:

  portainer:
    container_name: vtalksnet_portainer
    hostname: portainer
    restart: on-failure
    image: portainer/portainer
    ports:
      - "9000:9000"

  nats:
    container_name: vtalksnet_nats
    hostname: nats
    restart: on-failure
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"

  postgres:
    container_name: vtalksnet_postgres
    hostname: postgres
    restart: on-failure
    image: postgres:alpine
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    container_name: vtalksnet_adminer
    hostname: adminer
    restart: on-failure
    image: adminer
    ports:
      - "8080:8080"

  nginx:
    container_name: vtalksnet_nginx
    hostname: nginx
    restart: on-failure
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - postgres
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx.vh.default.conf:/etc/nginx/conf.d/default.conf:ro

  web:
    container_name: vtalksnet_web
    hostname: web
    restart: always
    image: vtalks/web:latest
    ports:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE
      - TWITTER_TOKEN
      - TWITTER_SECRET
      - YOUTUBE_API_KEY
      - COVERALLS_REPO_TOKEN
      - MAILGUN_API_KEY
      - MAILGUN_SMTP_PASSWORD
      - MAILGUN_SMTP_USER
    depends_on:
      - postgres
      - nats

  twitter-worker:
    container_name: vtalksnet_twitter_worker
    hostname: twitter-worker
    image: vtalks/twitter-worker:latest
    environment:
      - TLKSIO_TWITTER_TOKEN
      - TLKSIO_TWITTER_SECRET
      - TLKSIO_TWITTER_ACCESS_TOKEN
      - TLKSIO_TWITTER_ACCESS_SECRET
      - YOUTUBE_API_KEY
    depends_on:
      - web
      - nats
