version: '3.3'

services:

  postgres:

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.vh.default.conf:/etc/nginx/conf.d/default.conf
      - ../vtalks.net/web/static:/static

  web:
    build: ../vtalks.net
    volumes:
      - ../vtalks.net:/opt/vtalks.net/
