version: '3.3'

services:

  nginx:
  #   volumes:
  #       - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
  #       - /opt/nginx/nginx.vh.default.conf:/etc/nginx/conf.d/default.conf
  #       - /opt/static:/static
  # docker-machine scp -r ./deploy/nginx vtalks:/opt/nginx
  # docker-machine scp -r ./web/static vtalks:/opt/static

  postgres:
    ports:
      - "5432"

  web:
    image: vtalks/web:latest
