version: '3.3'

volumes:

  postgres-data:
    driver: local

  elasticsearch-data:
    driver: local

  pipeline-data:
    driver: local

services:

  portainer:
    container_name: vtalksnet_portainer
    hostname: portainer
    restart: on-failure
    image: portainer/portainer
    ports:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nats:
    container_name: vtalksnet_nats
    hostname: nats
    restart: on-failure
    image: nats
    ports:
      - "4222"
      - "8222"
      - "6222"

  postgres:
    container_name: vtalksnet_postgres
    hostname: postgres
    restart: on-failure
    image: postgres:alpine
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    container_name: vtalksnet_adminer
    hostname: adminer
    restart: on-failure
    image: adminer
    ports:
      - "8080"
    depends_on:
      - postgres

  elasticsearch:
    container_name: vtalksnet_elasticsearch
    hostname: elasticsearch
    restart: on-failure
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    ports:
      - "9200"
      - "9300"
    environment:
      - discovery.type=single-node
      - cluster.name=vtalks-elasticsearch
      - bootstrap.memory_lock=true
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: vtalksnet_kibana
    hostname: kibana
    restart: on-failure
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    ports:
      - "5601"

  nginx:
    container_name: vtalksnet_nginx
    hostname: nginx
    restart: on-failure
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx.vh.default.conf:/etc/nginx/conf.d/default.conf:ro

  web:
    container_name: vtalksnet_web
    hostname: web
    restart: always
    image: vtalks/web:latest
    ports:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE
      - TWITTER_TOKEN
      - TWITTER_SECRET
      - YOUTUBE_API_KEY
      - MAILGUN_API_KEY
      - MAILGUN_SMTP_PASSWORD
      - MAILGUN_SMTP_USER
    depends_on:
      - postgres
      - nginx

  updater-worker:
    container_name: vtalksnet_updater_worker
    hostname: updater-worker
    image: vtalks/updater-worker:latest
    environment:
      - YOUTUBE_API_KEY
    depends_on:
      - web

  twitter-worker:
    container_name: vtalksnet_twitter_worker
    hostname: twitter-worker
    image: vtalks/twitter-worker:latest
    environment:
      - TLKSIO_TWITTER_TOKEN
      - TLKSIO_TWITTER_SECRET
      - TLKSIO_TWITTER_ACCESS_TOKEN
      - TLKSIO_TWITTER_ACCESS_SECRET
    depends_on:
      - web

  facebook-worker:
    container_name: vtalksnet_facebook_worker
    hostname: facebook-worker
    image: vtalks/facebook-worker:latest
    depends_on:
      - web

  linkedin-worker:
    container_name: vtalksnet_linkedin_worker
    hostname: linkedin-worker
    image: vtalks/linkedin-worker:latest
    depends_on:
      - web

  pipeline:
    container_name: vtalksnet_data_pipeline
    hostname: pipeline
    restart: always
    image: vtalks/pipeline:latest
    environment:
      - YOUTUBE_API_KEY
      - PYTHONPATH=$PYTHONPATH:/opt/pipeline/tasks/
    ports:
      - "8082"
      - "9001"
    volumes:
      - pipeline-data:/opt/pipeline/data
      - ./pipeline/supervisord.conf:/etc/supervisord.conf:ro
      - ./pipeline/supervisord-luigi.ini:/etc/supervisor.d/supervisord-luigi.ini:ro