version: '3.3'

services:

  postgres:
    ports:
      - "5432:5432"

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx.vh.default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../vtalks.net/static:/static

  web:
    build: ../vtalks.net
    ports:
      - "8000:8000"
    volumes:
      - ../vtalks.net:/opt/vtalks.net/
