version: '3.3'

services:

  twitter-worker:
    build: ../twitter_worker
    volumes:
      - ../twitter_worker:/opt/twitter_worker

  postgres:
    ports:
      - "5432:5432"
    volumes:
      - ../.backup:/backup
      - ./postgres/restoredb.sh:/restoredb.sh:ro
      - ./postgres/dumpdb.sh:/dumpdb.sh:ro

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx.vh.default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../vtalks.net/static:/static

  web:
    build: ../vtalks.net
    ports:
      - "8000:8000"
    volumes:
      - ../vtalks.net:/opt/vtalks.net/
