version: '3.3'

services:

  nats:
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"

  postgres:
    ports:
      - "5432:5432"
    volumes:
      - ../.backup:/.backup
      - ./postgres/restoredb.sh:/restoredb.sh:ro
      - ./postgres/dumpdb.sh:/dumpdb.sh:ro

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/create_index.sh:/create_index.sh:ro
      - ./elasticsearch/delete_index.sh:/delete_index.sh:ro
      - ./elasticsearch/status.sh:/status.sh:ro

  kibana:
    ports:
      - "5601:5601"

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx.vh.default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../vtalks.net/static:/static

  web:
    build: ../vtalks.net
    ports:
      - "8000:8000"
    volumes:
      - ../.dataset:/.dataset
      - ../vtalks.net:/opt/vtalks.net/

  updater-worker:
    build: ../updater_worker
    volumes:
      - ../updater_worker:/opt/updater_worker

  twitter-worker:
    build: ../twitter_worker
    volumes:
      - ../twitter_worker:/opt/twitter_worker

  facebook-worker:
    build: ../facebook_worker
    volumes:
      - ../facebook_worker:/opt/facebook_worker

  linkedin-worker:
    build: ../linkedin_worker
    volumes:
      - ../linkedin_worker:/opt/linkedin_worker

  pipeline:
    build: ../pipeline
    ports:
      - "8082:8082"
    volumes:
      - ../pipeline:/opt/pipeline/

  pipeline-scheduler:
    volumes:
      - ../pipeline_scheduler:/opt/pipeline:_scheduler
