version: '3.3'

services:

  postgres:
    ports:
      - "5432"
    volumes:
      - /home/raul/Projects/vtalks/.backup:/.backup
      - /home/raul/Projects/vtalks/deploy/postgres/restoredb.sh:/restoredb.sh:ro
      - /home/raul/Projects/vtalks/deploy/postgres/dumpdb.sh:/dumpdb.sh:ro

  elasticsearch:
    ports:
      - "9200"
      - "9300"
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - /home/raul/Projects/vtalks/deploy/elasticsearch/create_index.sh:/create_index.sh:ro
      - /home/raul/Projects/vtalks/deploy/elasticsearch/delete_index.sh:/delete_index.sh:ro
      - /home/raul/Projects/vtalks/deploy/elasticsearch/status.sh:/status.sh:ro

  nginx:
    ports:
      - "80:80"
    volumes:
        - /home/raul/Projects/vtalks/deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
        - /home/raul/Projects/vtalks/deploy/nginx/nginx.vh.default.conf:/etc/nginx/conf.d/default.conf
        - /home/raul/Projects/vtalks/vtalks.net/static:/static

  web:
    ports:
      - "8000"
    volumes:
      - /home/raul/Projects/vtalks/.dataset:/.dataset
    image: vtalks/web:latest

  pipeline:
    ports:
      - "8082"
    image: vtalks/pipeline:latest
