version: '3.3'

volumes:

  postgres-data:
    driver: local

services:

  postgres:
    container_name: vtalksnet_postgres
    hostname: postgres
    restart: on-failure
    image: postgres:alpine
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../.backup:/backup
      - ./postgres/restoredb.sh:/restoredb.sh:ro
      - ./postgres/dumpdb.sh:/dumpdb.sh:ro

  nginx:
    container_name: vtalksnet_nginx
    hostname: nginx
    restart: on-failure
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - postgres
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx.vh.default.conf:/etc/nginx/conf.d/default.conf:ro

  web:
    container_name: vtalksnet_web
    hostname: web
    restart: always
    image: vtalks/web:latest
    ports:
      - "8000"
    environment:
      - TWITTER_TOKEN
      - TWITTER_SECRET
      - YOUTUBE_API_KEY
      - COVERALLS_REPO_TOKEN
    depends_on:
      - postgres
